### ISSUE TITLE
Ubuntu 17.10 EOL

### ISSUE THREAD

**Issue by Bebbolus** [xperimental/autoocr#2]
_ISSUE_: can't rebuild the docker image from actual Dockerfile, error from consolle:
"**The repository 'http://security.ubuntu.com/ubuntu artful-security Release' does not have a Release file**."

_DESCRIPTION_: the repository (autoocr) have not setted the version of the library and software that is in use but in Dockerfile is possible to see that we uses Ubuntu 17.10 that is actually end of life, so we can't refer to archive.ubuntu.com as ubuntu repository mirror.

_ANALYSIS_: please refer to https://askubuntu.com/questions/1141501/i-cant-run-sudo-apt-get-update-in-ubuntu-17-10

_SOLUTION_: add the following command to Dockerfile before apt-get update:
`RUN sed -i -re 's/([a-z]{2}\.)?archive.ubuntu.com|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list`

**Comment by xperimental** [comment]
Thanks for your input @Bebbolus !

I am currently on vacation, I'll look into this when I am back.

**Comment by xperimental** [comment]
Hi @Bebbolus, I went a slightly different route and have updated the underlying Ubuntu version to the current one. Can you check if that fixes your issue?
